/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutIndexImport } from './routes/_mainLayout/index'
import { Route as MainLayoutAccountsImport } from './routes/_mainLayout/accounts'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  id: '/_mainLayout/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutAccountsRoute = MainLayoutAccountsImport.update({
  id: '/_mainLayout/accounts',
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/accounts': {
      id: '/_mainLayout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof MainLayoutAccountsImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/': {
      id: '/_mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/accounts': typeof MainLayoutAccountsRoute
}

export interface FileRoutesByTo {
  '/': typeof MainLayoutIndexRoute
  '/accounts': typeof MainLayoutAccountsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_mainLayout/accounts': typeof MainLayoutAccountsRoute
  '/_mainLayout/': typeof MainLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts'
  id: '__root__' | '/' | '/_mainLayout/accounts' | '/_mainLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MainLayoutAccountsRoute: typeof MainLayoutAccountsRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MainLayoutAccountsRoute: MainLayoutAccountsRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_mainLayout/accounts",
        "/_mainLayout/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_mainLayout/accounts": {
      "filePath": "_mainLayout/accounts.tsx"
    },
    "/_mainLayout/": {
      "filePath": "_mainLayout/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
