/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutCategoriesImport } from './routes/_mainLayout/categories'
import { Route as MainLayoutAccountsImport } from './routes/_mainLayout/accounts'
import { Route as MainLayoutSettingsSectionImport } from './routes/_mainLayout/settings.$section'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MainLayoutCategoriesRoute = MainLayoutCategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAccountsRoute = MainLayoutAccountsImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutSettingsSectionRoute = MainLayoutSettingsSectionImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => MainLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/accounts': {
      id: '/_mainLayout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof MainLayoutAccountsImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/categories': {
      id: '/_mainLayout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainLayoutCategoriesImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/settings/$section': {
      id: '/_mainLayout/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof MainLayoutSettingsSectionImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

interface MainLayoutRouteChildren {
  MainLayoutAccountsRoute: typeof MainLayoutAccountsRoute
  MainLayoutCategoriesRoute: typeof MainLayoutCategoriesRoute
  MainLayoutSettingsSectionRoute: typeof MainLayoutSettingsSectionRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAccountsRoute: MainLayoutAccountsRoute,
  MainLayoutCategoriesRoute: MainLayoutCategoriesRoute,
  MainLayoutSettingsSectionRoute: MainLayoutSettingsSectionRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof MainLayoutRouteWithChildren
  '/accounts': typeof MainLayoutAccountsRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof MainLayoutRouteWithChildren
  '/accounts': typeof MainLayoutAccountsRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_mainLayout/accounts': typeof MainLayoutAccountsRoute
  '/_mainLayout/categories': typeof MainLayoutCategoriesRoute
  '/_mainLayout/settings/$section': typeof MainLayoutSettingsSectionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/accounts' | '/categories' | '/settings/$section'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/accounts' | '/categories' | '/settings/$section'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/_mainLayout/accounts'
    | '/_mainLayout/categories'
    | '/_mainLayout/settings/$section'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MainLayoutRoute: MainLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_mainLayout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/accounts",
        "/_mainLayout/categories",
        "/_mainLayout/settings/$section"
      ]
    },
    "/_mainLayout/accounts": {
      "filePath": "_mainLayout/accounts.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/categories": {
      "filePath": "_mainLayout/categories.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/settings/$section": {
      "filePath": "_mainLayout/settings.$section.tsx",
      "parent": "/_mainLayout"
    }
  }
}
ROUTE_MANIFEST_END */
