FROM postgres:latest

# RUN apt-get update && apt-get install -y \
#     postgresql-server-dev-all \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*

# RUN git clone https://github.com/pgvector/pgvector.git /usr/src/pgvector && \
#     cd /usr/src/pgvector && \
#     make && make install && \
#     rm -rf /usr/src/pgvector
